[functions]
  directory = "netlify_functions"

[build]
  function = "cors"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/cors/https://app.gridpaneapp.com/"
  status = 200
  force = true
  headers = {X-From = "netlify123", Host = "gridpaneapp.com"}