[[redirects]]
  from = "/*"
  to = "https://gridpaneapp.com"
  status = 200
  [redirects.headers]
    Accept = "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
    Host = "gridpaneapp.com"
    Refferer Policy = "strict-origin-when-cross-origin"
    Refferer = "https://gridpaneapp.com"
