[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "https://kind-mayer-9dddf0.netlify.app/https://app.gridpaneapp.com/:splat"
  status = 200
  force = true
  headers = {X-From = "netlify123", Host = "gridpaneapp.com"}
 

