[build]
  function = "netlify_functions"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "https://app.gridpaneapp.com/api/*"
  to = "/.netlify/functions/cors/https://app.gridpaneapp.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "netlify123", Host = "gridpaneapp.com", Origin = "gridpaneapp.com"}

[[redirects]]
  from = "/*"
  to = "https://app.gridpaneapp.com/:splat"
  status = 200
  force = true
  headers = {X-From = "netlify123", Host = "gridpaneapp.com", Origin = "gridpaneapp.com"}