[functions]
  directory = "netlify_functions"

[build]
  function = "cors"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/api/1.1/init/data?location=https://gridpaneapp.com*/"
  to = "/api/api/1.1/init/data?location=https://app.gridpaneapp.com*/""
  status = 200
  force = true
  headers = {X-From = "netlify123", Host = "gridpaneapp.com"}

  [[redirects]]
  from = "/*"
  to = "https://app.gridpaneapp.com/:splat"
  status = 200
  force = true
  headers = {X-From = "netlify123", Host = "gridpaneapp.com"}