[[headers]]
    for = “/*”
    [headers.values]
      Access-Control-Allow-Origin = “*”
      Host = "gridpaneapp.com"
      
[[redirects]]
  from = "/*"
  to = "https://gridpaneapp.com/"
  status = 200
  force = true
