[[headers]]
  Define which paths this specific [[headers]] block will cover.
    for = “/api/*”
    [headers.values]
      Access-Control-Allow-Origin = “**”
      Host = "gridpaneapp.com"
      
[[redirects]]
  from = "/*"
  to = "https://gridpaneapp.com/"
  status = 200
  force = true
