[functions]
  directory = "netlify_functions"

[build]
  function = "cors"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/1.1/init/data?location=https%3A%2F%2Fgridpaneapp.com%2F"
  to = "https://app.gridpane.co/api/1.1/init/data?location=https%3A%2F%2Fapp.gridpaneapp.com%2F"
  status = 200
  force = true
  headers = {X-From = "netlify123", Host = "gridpaneapp.com"}

  [[redirects]]
  from = "/"
  to = "https://app.gridpaneapp.com/"
  status = 200
  force = true
  headers = {X-From = "netlify123", Host = "gridpaneapp.com"}