[functions]
  directory = "netlify_functions"

[build]
  functions = "netlify_functions"

[dev]
  funtions = "netlify_functions"
  publish = "/"
  
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "https://gridpaneapp.com/api/*"
  to = "https://gridpaneapp.com/.netlify/functions/cors/splat:"
  status = 200
  force = true
  headers = {X-From = "netlify123", Host = "gridpaneapp.com", Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "https://app.gridpaneapp.com/:splat"
  status = 200
  force = true
  headers = {X-From = "netlify123", Host = "gridpaneapp.com", Access-Control-Allow-Origin = "*"}