[functions]
  directory = "netlify_functions"

[build]
  function = "cors"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "https://app.gridpaneapp.com/:splat"
  status = 200
  force = true
  headers = {X-From = "netlify123", Host = "gridpaneapp.com"}
    
    [redirects.headers]
      Host = "gridpaneapp.com"
      Access-Control-Allow-Origin = "*"